in-toto/witness

- examples/log4shell/verify.sh
- pkg/policy/errors.go
- pkg/policy/policy.go
- pkg/policy/rego.go
- pkg/policy/step.go
Attestation collections were incorrectly being considered to have passed
the policy if any of the attestations passed, even if others failed.
This was due to the collection being added to the Passed slice multiple
times for each attestation that didn't result in a failure.  Properly
breaking out of the inner loop and only considering a collection as
passed when all of it's attestations pass fixes the issue.
> bug: fix incorrect policy evaluation

- cmd/witness/cmd/root.go
- cmd/witness/cmd/sign.go
- cmd/witness/cmd/verify.go
- pkg/attestors.go
Moves all attestor imports to the witness package so anyone using
witness as a library will have all the stock attestors.
Fixes #148
> refactor: move attestor imports to pkg

- pkg/attestation/scorecard/scorecard.go
- pkg/attestors.go
The two newly added attestors were not imported so their init functions
would not have run. Also the scorecard attestor had references to sarif
incorrectly.
> bug: ensure sarif and scorecard packages are imported

- go.mod
- go.sum
- pkg/rekor/rekor.go
Requires custom rekor installation from
https://github.com/testifysec/rekor on the dsse-intermediates branch
currently.  This will use any intermediates from rekor when verifying
signatures from x509 certificates.
> fix: use intermediates from rekor

- pkg/cryptoutil/x509.go
- pkg/dsse/dsse.go
- pkg/rekor/rekor.go
Few different issues here
* Intermediates from rekor need to be base64 decoded before using them.
* Trusted time stamps were only being considered while parsing entries
from rekor but not while verifying envelopes in witness.Verify. To get
around this I added an option to attach a trusted time to a specific
DSSE signature which makes sure this gets used when verifying the
envelopes.
> bug: fix verification of attestations from rekor

- pkg/rekor/rekor.go
the file backref causes too many lookups.
> Remove file backref

- examples/log4shell/build.sh
- examples/log4shell/find-affected-artifacts.sh
- examples/log4shell/verify.sh
- examples/solarwinds/demo.sh
- test/common.sh
- test/test-oci.sh
Just adds some friendlier messages when running our test and example
scripts.  This came up when a developer tried to use the scripts and
encountered errors.
> chore: add guards to scripts to check presence of required programs

- cmd/root.go
- cmd/verify_test.go
This is happening due to the order in which Cobra is running functions. Previously we were initializing our logging library in a Cobra OnInitialize function but this function gets run after Cobra has parsed the command line flags.
This resulted in our logging not being appropriately initialized so the error was being suppressed. By initializing our logger in the New function and only setting the level in the OnInitialize the unknown flag error gets logged appropriately.
Fixes #203
> chore: add logging when an unknown flag is provided

- .github/workflows/scorecard.yml
- README.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
The only thing that @colek42 you have to do is create a token with the required permissions and set it as a secret:
> github.com/ossf/scorecard-action#authentication-with-pat
> https://github.com/ossf/scorecard-action#installation
> https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
> chore: scorecard workflow added

- .github/workflows/release.yml
- .goreleaser.yaml
Currently errors from fulcio are breaking our release cycle. We will need to take a look at what is going on, but for now we're temporarily removing sigstore signing from our actions.
> chore: temporarily remove sigstore

- install-witness.sh
removes the need for jq and sudo
better logic for checking checksums
adds an argument so that the user can install it in any directory
asks for a password if sudo is required
> fix:various fixes and improvements in install script

- cmd/verify.go
- cmd/verify_test.go
`witness verify` previously required an artifact file to be provided to verify. Additional subjects were also able to be provided, but some users wanted the ability to verify without an artifact file path and only subjects.
> refactor: allow only subjects to be provided to witness verify

- .github/workflows/release.yml
Same as https://github.com/testifysec/archivista/pull/54
> fix: update goreleaser action to use go 1.20.x

- .github/workflows/release.yml
- .github/workflows/test-github-token.yml
Updates to a newer version of the witness-run-action with the updated fulcio url as well as updates our tests to use the new fulcio url.
> fix: update github actions to use new fulcio url

- README.md
A recent update changed the value for the key location from `key` to `signer-file-key-path`, this updates the Getting Started portion to reflect that change:
See https://github.com/testifysec/witness/pull/276/files#diff-a2d81e76a54ef2f17702a8b6de2fac6a61330f3585b3204f0463b3fa880c0f70L16
and current open issue: https://github.com/testifysec/witness/issues/287
> docs: Update key to signer-file-key-path in getting starter .witness.yaml

- README.md
Fixup of https://github.com/in-toto/witness/pull/289
Before
```
witness sign -f policy.json --key testkey.pem --outfile policy-signed.json
ERROR   unknown flag: --key 
```
After
```
witness sign -f policy.json --signer-file-key-path testkey.pem --outfile policy-signed.json
INFO    Using config file: .witness.yaml   
```
> docs: correct sign policy file command in README.md

- cmd/run.go
- cmd/run_test.go
- docs/witness_run.md
- options/run.go
Introduce flag that allows for slice of string's indicating hash algorithms to be used for digest calculation. Uses go-witness.attestation.WithHashes to add the slice to attestation run options. Will error if can't parse hash from its string value.
Add to run tests to test for acceptable/unacceptable hash algorithms accepted
Refs: #73
> feat: add algo hash list for digest calc in config

- cmd/run.go
- cmd/verify.go
- cmd/verify_test.go
- go.mod
- go.sum
This is a quick PR after noticing that `witness/main` does not work with `go-witness` main due to changes merged in https://github.com/in-toto/go-witness/pull/139.
@mikhailswift I *set the `GitOID` field to `false`* everywhere, which I am not 100% is correct. If you could give this a review, please let me know if these fields need set differently.
> Updated witness to use changes made to `cryptoutil.DigestValue` implemented in go-witness

- MAINTAINERS.md
Add Tom as an official Witness maintainer after all the great work and contributions he's made. 🎉
> Add Tom as a Witness maintainer

- .github/workflows/release.yml
This runs the test script in test.sh, which tests a few end to end policy verification test cases.
This will fail until https://github.com/in-toto/go-witness/pull/173 is merged and the dependency updated.
Fixes #
> fix: run e2e test script as part of workflows

- CONTRIBUTING.md
fixes #452 
1. Changed the link for the installation of GNU Make.
2. Changed the link for forking the repository.
3. Changed the link for setting up a remote repository.
> Changed all the broken links

- install-witness.sh
The install-witness.sh script did not work on macOS due to the absence of the sha256sum command.
This patch adds a check to use shasum -a 256 if sha256sum is not available, ensuring the script
runs correctly on macOS.
- Added a conditional check to use shasum -a 256 when sha256sum is not found
- Updated the FILE_CHECKSUM assignment to support both commands
Closes #458
Signed-off-by: Frederick F. Kautz IV <frederick@testifysec.com>
> fix(install-witness.sh): ensure compatibility with macOS for checksum verification

- docs/tutorials/getting-started.md
This PR results in a short discussion on [Slack](https://cloud-native.slack.com/archives/C068F87H1MF/p1716556723201989?thread_ts=1714982522.789209&cid=C068F87H1MF).
The Provenance being the very first requirement from SLSA, it seems quite appropriate to mention how Witness helps achieve this easily.
> docs(getting-started): add information about slsa attestor

- .github/workflows/release.yml
- .goreleaser.yaml
Added sbom generation of artifacts using syft
Fixes #437
> Added generation of SBOM

- .goreleaser.yaml
Temporarily remove Windows arm64 builds
> Remove Windows Arm64 build until fixed

- .goreleaser.yaml
- go.mod
- go.sum
This updates go-witness to v0.5.2 which includes a build directive to disable compilation of the omnitrail attestor when targeting Windows.
Description
Fixes #
> fix: temporarily disable omnitrail on windows builds

- cmd/verify.go
Add logging of passed step if found during policy failure. It's possible individual steps may pass but, the larger policy fails.
> Add logging of passed step if found during policy failure

- docs/commands.md
- options/run.go
Refactor: Simple nitpick refactor to have all run option flags have shorthand vars.
Description
I was looking at my old PR that added hashes as run options flags and realized it and others did not have shorthand vars like the majority of the run options flags. So, I threw this nit PR up just in case y'all believe its best to align and have all run options flags have shorthand vars.
Feel free to close PR if you don't agree.
> refactor: make all run options have shorthand vars

- cmd/keyloader.go
During verification there is nondeterministic behavior if the flag `--verifier-kms-aws-remote-verify=[true/false]` is not specified. I found that this is because there is an early return causing the default boolean `true` value to not be set for the `verifyRemotely` attribute.
In some instances, the first `ksp` in the outer loop will be `kms-gcp`. If using an AWS reference, then the proper verifyRemotely setter will not be run. Other times, the first `ksp` will be `kms-aws` and the proper setter will be called.
You can check this by running `witness verify --verifier-kms-ref [KMS_REF] -a [ATTESTATION] -f [ARTIFACT] -p policy.signed.json` using an AWS IAM account without the `Verify` permission. It will succeed sometimes and fail other times.
> prevent early return in verifier

- cmd/run.go
- cmd/verify.go
- cmd/verify_test.go
- docs/commands.md
- docs/tutorials/getting-started.md
- options/run.go
- options/verify.go
Adding the dirhash-glob arguments
Depends on: 
Fixes: #216 and https://github.com/in-toto/go-witness/issues/65
- idea to add subject types to the attestor documentation for easier understanding of the different subjects.
- examples or reasoning for using dirhash. also mentioning the downsides for certain use cases.
> Adding functionality for dirhash in cli

- .github/workflows/release.yml
- .github/workflows/witness.yml
Update install path so as to not dirty git state.
> Use /usr/local/bin for witness install

- .gitlab-ci.yml
The gitlab ci file used an old version of golang that does not match the project.
Fixes #
> chore: Fix gitlab image to correct golang version 1.23.2

- cmd/run.go
- docs/attestors/environment.md
- docs/commands.md
- options/run.go
Description
changed --env-exclude-sensitive-key to --env-allow-sensitive-key
https://github.com/in-toto/witness/issues/556
Fixes #
> changed --env-exclude-sensitive-key to --env-allow-sensitive-key

- README.md
- netlify.toml
This PR adds TestifySec sponsorship information to the README and fixes a Netlify build issue.
- Added sponsorship banner after badges section in README
- Highlights TestifySec's enterprise platform for attestation storage, visualization, and management
- Includes contact link for enterprise support inquiries
- Disabled Netlify smart detection to resolve false positive in secrets scanner
- The scanner was detecting 'LS0t' (base64 for '---') from PEM headers in build output
> docs: add TestifySec sponsorship to README

- docs-website/docusaurus.config.js
There is announcement bar at the top of every page on https://witness.dev/. This announcement bar is now completely outdated and (as far as I know) lost on an old Google account of mine. This PR removes it.
I'm also pretty sure that this will require a redeploy on Netlify? cc'ing @colek42.
> Remove announcement bar with docs survey callout

- cmd/root.go
- cmd/version.go
- cmd/version_test.go
Improve test coverage - added a test for `cmd/version.go`
Ref: https://github.com/in-toto/witness/pull/571 (from this pr)
Description
Part of #634
> test: add cmd/version.go

- docs/signers/kms.md
I was reading about the `KMS Signer` and found out that the `Sigstore Cosign project` overview link is incorrect
Description
Fixes #
> fix the link of Sigstore Cosign project
