README.md
docs/policy.md
test/policy.json

docs: add documentation for the policy verification process

---

.goreleaser.yaml
Makefile
cmd/witness/cmd/root.go
cmd/witness/cmd/version.go
docs/witness.md
docs/witness_version.md

Adds command to print version based on tags.

Add command to print version

---

pkg/attestation/scorecard/scorecard.go

This PR adds support for parsing scorecard reports as a post attestor
https://asciinema.org/a/S79NrIsiuX4LubgudVYIc0GSB
fixes #146

OpenSSF Scorecard Attestor

---

go.mod
go.sum
pkg/attestation/sarif/sarif.go

This MR adds support for creating attestations from tools that output sarif type reports.  fixes #143

SARIF Attestor

---

pkg/attestation/commandrun/commandrun.go
pkg/attestation/commandrun/tracing_linux.go
pkg/attestation/environment/blocklist.go
pkg/attestation/environment/environment.go
pkg/attestation/environment/environment_test.go

Uses the list from https://github.com/Puliczek/awesome-list-of-secrets-in-environment-variables/blob/main/raw_list.txt
but allows for the configuration of custom block lists.
https://github.com/testifysec/witness/issues/170

feat: block known sensitive environment variables

---

.github/workflows/scorecard.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Duplicates with #210 
/cc @mikhailswift @naveensrinivasan @krol3

chore: upgrade scorecard version

---

cmd/run.go
cmd/sign.go
cmd/verify_test.go
docs/witness_run.md
docs/witness_sign.md
go.mod
go.sum
options/run.go
options/sign.go

feat: add timestamping options

---

.github/workflows/release.yml
.goreleaser.yaml

This PR uses our own tooling to generate attestations and SBOMs for releases
test run:  https://github.com/testifysec/witness/actions/runs/3303477542/jobs/5451458947

chore: dog food witness

---

README.md

chore: fix documentation

---

.github/workflows/release.yml

this is after the release pipeline failed :thisisfine:

Bumping Go version for goreleaser

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

I'd love feedback no these. We can add corresponding templates to go-witness and archivista too, if they're useful.

Initial attempt at PR and Issue templates

---

README.md

Adds back missing license scanning badge.

Add back license scanning badge

---

docs/signers/kms.md

Fix the example. The step name needs to be included.
Remove some trailing white spaces.
None
None

doc: fix example in signers kms doc

---

docs-website/yarn.lock
netlify.toml

Netlify builds are not going through as they're being ignored. The ignore in the config will be the root cause

Updating yarn and modifying ignore on netlify toml

---

Makefile

Small improvement to allow local goreleaser builds. Which is easy for cross platform builds.
-

chore: Allow make build-goreleaser for convenience.

---

Makefile

Add help messages for build and build-goreleaser

docs: update Makefile help

---

.goreleaser.yaml

Add pem as output of goreleaser sign for verification.
Addresses requirement for 
- https://github.com/in-toto/witness/issues/418

Add pem as output of goreleaser sign for verification.

---

docs/attestors/environment.md

Adding proper documentation on the configuration of environment attestor.
None

chore: Add documentation on environment attestor

---

cmd/keyloader.go
docs/attestors/material.md
docs/attestors/maven.md
docs/concepts/config.md
docs/concepts/policy.md
docs/tutorials/sigstore-keyless.md

chore: fix some comments

---

README.md

- Add Witness origin statement at the top of README
- Remove sponsorship notice  
- Replace Background section with Community & Commercial Support section
- Add links to TestifySec

Update README with origin statement and support information

---

docs/tutorials/getting-started.md

Small improvement to docs site. Getting started is sorted at the top of the tutorials for easier and more logical viewing.

Make getting started the first item.

---

options/root_test.go

Description
added test for the options/root.go
Part of https://github.com/in-toto/witness/issues/634

test: added for the options/root.go

---

options/verify_test.go

Description
added for the options/verify.go
Part of https://github.com/in-toto/witness/issues/634

test: added for the options/verify.go

---

cmd/attestors_test.go
cmd/completion_test.go

Description
added test for the attestor and completion
Part of #634

feat: added test for the cmd/attestors and cmd/completion
